version: '3.8'

services:
  backend:
    build: .
    container_name: anime-backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - AZURE_OPENAI_APIKEY=${AZURE_OPENAI_APIKEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}

  frontend:
    build: .
    container_name: anime-frontend
    command: streamlit run app/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FASTAPI_URL=http://backend:8000
    depends_on:
      - backend
